"""add branch and zone models

Revision ID: 1c2d3e4f5a6b
Revises: 9b7c1d2a4e5f
Create Date: 2026-02-05 21:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1c2d3e4f5a6b"
down_revision = "9b7c1d2a4e5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "zone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branch.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("leader", schema=None) as batch_op:
        batch_op.add_column(sa.Column("zone_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_leader_zone", "zone", ["zone_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leader", schema=None) as batch_op:
        batch_op.drop_constraint("fk_leader_zone", type_="foreignkey")
        batch_op.drop_column("zone_id")
    op.drop_table("zone")
    op.drop_table("branch")
    # ### end Alembic commands ###
