"""add user role and leader link

Revision ID: 2a3b4c5d6e7f
Revises: 1c2d3e4f5a6b
Create Date: 2026-02-05 22:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a3b4c5d6e7f"
down_revision = "1c2d3e4f5a6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("role", sa.String(length=20), nullable=False, server_default="user")
        )
        batch_op.add_column(sa.Column("leader_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_user_leader", "leader", ["leader_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_leader", type_="foreignkey")
        batch_op.drop_column("leader_id")
        batch_op.drop_column("role")
    # ### end Alembic commands ###
