"""initial

Revision ID: 5f4e6750b9e0
Revises: 
Create Date: 2026-02-05 18:56:53.280586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4e6750b9e0'
down_revision = None
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names())

    if 'user' not in existing:
        op.create_table(
            'user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=80), nullable=False),
            sa.Column('password_hash', sa.String(length=255), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    if 'leader' not in existing:
        op.create_table(
            'leader',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('zone', sa.String(length=50), nullable=False),
            sa.Column('cell_day', sa.String(length=20), nullable=True),
            sa.Column('contact_number', sa.String(length=20), nullable=True),
            sa.Column('email', sa.String(length=100), nullable=True),
            sa.Column('address', sa.Text(), nullable=True),
            sa.Column('profile_picture', sa.String(length=255), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    if 'service_record' not in existing:
        op.create_table(
            'service_record',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('leader_id', sa.Integer(), nullable=False),
            sa.Column('service_type', sa.String(length=20), nullable=False),
            sa.Column('service_date', sa.Date(), nullable=False),
            sa.Column('sunday_attendance', sa.Integer(), nullable=True),
            sa.Column('sunday_visitors', sa.Integer(), nullable=True),
            sa.Column('cell_attendance', sa.Integer(), nullable=True),
            sa.Column('cell_visitors', sa.Integer(), nullable=True),
            sa.Column('cell_offering', sa.Float(), nullable=True),
            sa.Column('cell_decisions', sa.Integer(), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('submitted_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['leader_id'], ['leader.id']),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names())

    if 'service_record' in existing:
        op.drop_table('service_record')

    if 'leader' in existing:
        op.drop_table('leader')

    if 'user' in existing:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_user_username'))
        op.drop_table('user')
    # ### end Alembic commands ###