"""add service_record unique constraint

Revision ID: 8f1b2f2c9c1a
Revises: 5f4e6750b9e0
Create Date: 2026-02-05 19:12:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f1b2f2c9c1a"
down_revision = "5f4e6750b9e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_record", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_service_record_leader_type_date",
            ["leader_id", "service_type", "service_date"],
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_record", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_service_record_leader_type_date",
            type_="unique",
        )
    # ### end Alembic commands ###
