"""add cancellation fields to service_record

Revision ID: 9b7c1d2a4e5f
Revises: 8f1b2f2c9c1a
Create Date: 2026-02-05 20:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b7c1d2a4e5f"
down_revision = "8f1b2f2c9c1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_record", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_cancelled", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(sa.Column("cancel_reason", sa.Text(), nullable=True))
    op.execute("UPDATE service_record SET is_cancelled = 0 WHERE is_cancelled IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_record", schema=None) as batch_op:
        batch_op.drop_column("cancel_reason")
        batch_op.drop_column("is_cancelled")
    # ### end Alembic commands ###
